stages:
  - secrets-scan

variables:
  GITLEAKS_REPORT: "gitleaks-report.json"
  GIT_STRATEGY: "clone"        # always do a fresh clone (no repo cache reuse)
  GIT_CHECKOUT: "true"         # ensure working tree is checked out
  GIT_DEPTH: "0"               # full history (set to "1" if you only need the tip)
  GIT_CLEAN_FLAGS: "-ffdx"     # wipe untracked + ignored files before checkout

gitleaks_scan:
  stage: secrets-scan
  image:
    name: zricethezav/gitleaks:v8.18.4 
    entrypoint: [""]   
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - gitleaks detect --source . --report-format json --report-path "$GITLEAKS_REPORT" --exit-code 1
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - $GITLEAKS_REPORT